// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNEYE4MUPyGsphmehpG4O2akHxrLKu0Pg',
    appId: '1:164716619247:web:9acb0ddd12161f476a421a',
    messagingSenderId: '164716619247',
    projectId: 'todo-app-79225',
    authDomain: 'todo-app-79225.firebaseapp.com',
    storageBucket: 'todo-app-79225.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpVOj1rHLaNWoJ3mSIRdWSuS9XW-ReMTo',
    appId: '1:164716619247:android:9ca37e0e68480aee6a421a',
    messagingSenderId: '164716619247',
    projectId: 'todo-app-79225',
    storageBucket: 'todo-app-79225.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIYlTsX8tUTesK6bqZ_rMZmXpiYDlBKhs',
    appId: '1:164716619247:ios:a0025c30e0cc271f6a421a',
    messagingSenderId: '164716619247',
    projectId: 'todo-app-79225',
    storageBucket: 'todo-app-79225.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIYlTsX8tUTesK6bqZ_rMZmXpiYDlBKhs',
    appId: '1:164716619247:ios:a0025c30e0cc271f6a421a',
    messagingSenderId: '164716619247',
    projectId: 'todo-app-79225',
    storageBucket: 'todo-app-79225.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNEYE4MUPyGsphmehpG4O2akHxrLKu0Pg',
    appId: '1:164716619247:web:3b1ada9cab3ed2f56a421a',
    messagingSenderId: '164716619247',
    projectId: 'todo-app-79225',
    authDomain: 'todo-app-79225.firebaseapp.com',
    storageBucket: 'todo-app-79225.appspot.com',
  );
}
